'use client';
import { useEffect, useRef, useState } from 'react';
import { Crosshair, RotateCcw, Play, Pause, Expand, Volume2, VolumeX, Shield, Zap } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Arena, type Settings, type Snapshot } from './trainer';
import { registerTrainerTools } from './webmcp';
const initial:Settings={attackSpeed:1.5,windup:22,moveSpeed:325,range:550,difficulty:'standard',mode:'mixed',quick:false,showRange:true,sound:true};
const empty:Snapshot={status:'idle',time:60,fired:0,cancelled:0,hits:0,dodged:0,moved:0,phase:'READY',progress:1,streak:0,best:0};
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),arena=useRef<Arena|null>(null);
 const [settings,setSettings]=useState(initial),[stats,setStats]=useState(empty);
 const config=(patch:Partial<Settings>)=>setSettings(s=>({...s,...patch}));
 useEffect(()=>{if(!canvas.current)return;const game=new Arena(canvas.current,initial,setStats);arena.current=game;const cleanup=registerTrainerTools(game);return()=>{cleanup();game.destroy();};},[]);
 useEffect(()=>{arena.current?.configure(settings);},[settings]);
 const active=stats.status==='running',locked=active||stats.status==='paused';
 return <main><header className="topbar"><a className="brand" href="/"><Crosshair size={25}/> ORBWALK<span className="brand-divider"/><span className="brand-sub">MECHANICS LAB</span></a><div className="top-note"><i className="live-dot"/>ADC TRAINING GROUND <span className="version">01 / BETA</span></div></header>
 <div className="workspace"><section className="play-column"><div className="section-top"><div><div className="eyebrow">MOVE WITH INTENT.</div><h1>The kiting lab<span>.</span></h1></div><div className="session-tag"><i className={active?'live-dot':'idle-dot'}/>{active?'SESSION LIVE':stats.status==='paused'?'PAUSED':'60 SECOND DRILL'}</div></div>
 <div className="arena-shell" id="arena-shell"><div className="arena-top"><span>◇ &nbsp;{settings.mode==='mixed'?'KITING + DODGING':settings.mode==='rhythm'?'ATTACK RHYTHM':'DODGE PRACTICE'}</span><div className="arena-actions"><button aria-label={settings.sound?'Mute sound':'Enable sound'} onClick={()=>config({sound:!settings.sound})}>{settings.sound?<Volume2 size={17}/>:<VolumeX size={17}/>}</button><button aria-label="Fullscreen arena" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.getElementById('arena-shell')?.requestFullscreen().catch(()=>{});}}><Expand size={17}/></button></div></div>
 <canvas ref={canvas} tabIndex={0} aria-label="Training arena. Right click to move. A then left click to attack move. Space to pause. S to stop."/>
 {(stats.status==='idle'||stats.status==='ended')&&<div className="start-overlay"><div className="start-card"><div className="overlay-icon"><Crosshair size={28}/></div><div className="eyebrow">{stats.status==='ended'?'SESSION COMPLETE':'FIND YOUR RHYTHM'}</div><h2>{stats.status==='ended'?`${stats.fired} attacks. Keep moving.`:'Attack. Move. Repeat.'}</h2><p>{stats.status==='ended'?`${stats.cancelled} cancelled attacks · ${stats.hits} skill-shot hits · ${Math.round(stats.moved)}% moving uptime`:'Release your shot, move through recovery, and stay clear of the red.'}</p><button className="primary-button" onClick={()=>arena.current?.start()}><Play size={16} fill="currentColor"/>{stats.status==='ended'?'Run it back':'Start training'}<span>↵</span></button><div className="desktop-hint">Mouse + keyboard · 60 seconds · No death penalty</div></div></div>}
 {stats.status==='paused'&&<div className="start-overlay"><div className="start-card"><div className="eyebrow">TAKE A BREATH</div><h2>Session paused</h2><p>Your session pauses when this window loses focus.</p><button className="primary-button" onClick={()=>arena.current?.togglePause()}><Play size={16}/>Resume training</button></div></div>}
 <div className="arena-bottom"><span><i className="legend cyan"/>YOU<i className="legend amber"/>TARGET<i className="legend red"/>DANGER</span><span>550 UNITS <i className="scale-line"/></span></div></div>
 <div className="timing-strip"><div className="phase-label"><Zap size={17}/>{stats.phase}</div><div className="timing-track"><div style={{width:`${stats.progress*100}%`}} className={stats.phase==='WINDUP'?'windup':''}/></div><span className="timing-hint">{stats.phase==='AIMING'?'Click to attack':stats.phase==='WINDUP'?'Hold for release':stats.phase==='RECOVERY'?'Move now':'Ready to attack'}</span><button className="icon-button" disabled={!locked} aria-label={active?'Pause session':'Resume session'} onClick={()=>arena.current?.togglePause()}>{active?<Pause size={17}/>:<Play size={17}/>}</button><button className="icon-button" aria-label="Restart session" onClick={()=>arena.current?.start()}><RotateCcw size={17}/></button></div>
 <div className="metrics"><Metric label="TIME LEFT" value={`${Math.ceil(stats.time)}`} unit="s"/><Metric label="ATTACKS FIRED" value={`${stats.fired}`} unit="shots"/><Metric label="CANCELLED" value={`${stats.cancelled}`} unit="attacks" warn={stats.cancelled>0}/><Metric label="DODGE RATE" value={stats.dodged+stats.hits?`${Math.round(stats.dodged/(stats.dodged+stats.hits)*100)}`:'—'} unit="%"/></div>
 <div className="control-guide"><div><kbd>RMB</kbd>Move</div><div><kbd>A</kbd>{!settings.quick&&<>then <kbd>LMB</kbd></>}Attack move</div><div><kbd>S</kbd>Stop</div><div><kbd>SPACE</kbd>Pause</div><span className="guide-tip">Move after the cyan flash.</span></div></section>
 <aside className="settings-panel"><div className="panel-heading"><h2>Training setup</h2><span>01</span></div><p className="panel-description">Build the rhythm. Turn up the pressure.</p>
 <div className="setting-section"><label className="eyebrow">DRILL</label><Tabs value={settings.mode} onValueChange={v=>config({mode:v as Settings['mode']})}><TabsList className="drill-tabs"><TabsTrigger disabled={locked} value="mixed">Kite + dodge</TabsTrigger><TabsTrigger disabled={locked} value="rhythm">Rhythm</TabsTrigger><TabsTrigger disabled={locked} value="dodge">Dodge</TabsTrigger></TabsList></Tabs><p className="setting-note">{settings.mode==='mixed'?'Moving targets. Incoming skill shots. Stay in motion.':settings.mode==='rhythm'?'No incoming damage. Focus on clean attack releases.':'No attack targets. Read the telegraphs and sidestep.'}</p></div>
 <div className="setting-section"><div className="eyebrow">MARKSMAN PROFILE</div><Range label="Attack speed" value={settings.attackSpeed} display={`${settings.attackSpeed.toFixed(2)} /s`} min={0.5} max={2.5} step={0.05} disabled={locked} change={v=>config({attackSpeed:v})}/><Range label="Windup" value={settings.windup} display={`${settings.windup}%`} min={15} max={40} step={1} disabled={locked} change={v=>config({windup:v})}/><Range label="Move speed" value={settings.moveSpeed} display={`${settings.moveSpeed}`} min={250} max={450} step={5} disabled={locked} change={v=>config({moveSpeed:v})}/><div className="profile-foot">550 attack range <span>•</span> {Math.round(1000/settings.attackSpeed*settings.windup/100)} ms windup</div></div>
 <div className="setting-section"><div className="eyebrow">SKILL-SHOT PRESSURE</div><Tabs value={settings.difficulty} onValueChange={v=>config({difficulty:v as Settings['difficulty']})}><TabsList className="pressure-tabs"><TabsTrigger disabled={locked} value="easy">Low</TabsTrigger><TabsTrigger disabled={locked} value="standard">Standard</TabsTrigger><TabsTrigger disabled={locked} value="hard">High</TabsTrigger></TabsList></Tabs><p className="setting-note">Line shots, spread volleys, and delayed ground bursts.</p></div>
 <div className="setting-section toggle-section"><label><span>One-key attack move<small>Press A to attack at cursor</small></span><Switch checked={settings.quick} onCheckedChange={v=>config({quick:v})} aria-label="One-key attack move"/></label><label><span>Show attack range</span><Switch checked={settings.showRange} onCheckedChange={v=>config({showRange:v})} aria-label="Show attack range"/></label></div>
 <div className="coach-note"><Shield size={20}/><div><strong>Clean release, then move.</strong><p>A move command during windup cancels your attack. The cyan flash is your cue to reposition.</p></div></div><div className="secondary-metrics"><div><span>Skill shots taken</span><b>{stats.hits}</b></div><div><span>Moving uptime</span><b>{Math.round(stats.moved)}%</b></div><div><span>Best dodge streak</span><b>{stats.best}</b></div></div></aside></div>
 <footer><span>↗ &nbsp; PRECISION OVER PANIC</span><span>Independent practice tool · Tunable timing, not a League client simulation</span></footer></main>;
}
function Metric({label,value,unit,warn=false}:{label:string;value:string;unit:string;warn?:boolean}){return <div className="metric"><span>{label}</span><div className={warn?'warn':''}>{value}<small>{unit}</small></div></div>;}
function Range({label,value,display,min,max,step,disabled,change}:{label:string;value:number;display:string;min:number;max:number;step:number;disabled:boolean;change:(v:number)=>void}){return <div className="range-setting"><div><label>{label}</label><output>{display}</output></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} disabled={disabled} onValueChange={v=>change(Array.isArray(v)?v[0]:v)}/></div>;}
