export type Settings={attackSpeed:number;windup:number;moveSpeed:number;range:number;difficulty:'easy'|'standard'|'hard';mode:'mixed'|'rhythm'|'dodge';quick:boolean;showRange:boolean;sound:boolean};
export type Snapshot={status:'idle'|'running'|'paused'|'ended';time:number;fired:number;cancelled:number;hits:number;dodged:number;moved:number;phase:string;progress:number;streak:number;best:number};
type Point={x:number;y:number};
type Target=Point&{id:number;flash:number};
type Danger=Point&{vx:number;vy:number;delay:number;age:number;life:number;radius:number;kind:'line'|'circle';hit:boolean;resolved:boolean};
type Effect=Point&{life:number;max:number;color:string;text?:string};
const W=1500,H=920,STEP=1/120;
export const distance=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y);
export function segmentDistance(p:Point,a:Point,b:Point){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;const t=l?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l)):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy);}
export class Simulation{
 settings:Settings;status:Snapshot['status']='idle';elapsed=0;player:Point={x:650,y:520};previous:Point={x:650,y:520};destination:Point|null=null;cursor:Point={x:850,y:450};armed=false;target:Target|null=null;attackOrder=false;windupLeft=0;cooldown=0;fired=0;cancelled=0;hits=0;dodged=0;movingTime=0;streak=0;best=0;flash=0;nextDanger=1.2;targets:Target[]=[];dangers:Danger[]=[];effects:Effect[]=[];bolts:(Point&{target:Target})[]=[];angle=0;shotEvent=0;hitEvent=0;
 constructor(settings:Settings){this.settings={...settings};this.resetTargets();}
 resetTargets(){this.targets=this.settings.mode==='dodge'?[]:[{x:970,y:400,id:1,flash:0},{x:1050,y:630,id:2,flash:0},{x:550,y:270,id:3,flash:0}];}
 start(){this.status='running';this.elapsed=0;this.player={x:650,y:520};this.previous={...this.player};this.destination=null;this.target=null;this.attackOrder=false;this.armed=false;this.windupLeft=0;this.cooldown=0;this.fired=0;this.cancelled=0;this.hits=0;this.dodged=0;this.movingTime=0;this.streak=0;this.best=0;this.flash=0;this.nextDanger=1.2;this.dangers=[];this.effects=[];this.bolts=[];this.resetTargets();}
 effect(p:Point,color:string,text?:string){this.effects.push({...p,color,text,life:text?0.8:0.35,max:text?0.8:0.35});}
 cancel(){if(this.windupLeft>0){this.cancelled++;this.windupLeft=0;this.cooldown=0;this.effect(this.player,'#ffb56c','CANCELLED');}}
 move(p:Point){if(this.status!=='running')return;this.cancel();this.attackOrder=false;this.target=null;this.armed=false;this.destination={x:Math.max(40,Math.min(W-40,p.x)),y:Math.max(55,Math.min(H-45,p.y))};this.effect(this.destination,'#63e7d0');}
 stop(){this.cancel();this.destination=null;this.attackOrder=false;this.target=null;this.armed=false;}
 attack(p:Point){if(this.status!=='running')return;this.armed=false;let candidates=this.targets.filter(t=>distance(t,p)<220);if(!candidates.length)candidates=this.targets.filter(t=>distance(t,this.player)<=this.settings.range);const t=candidates.sort((a,b)=>distance(a,p)-distance(b,p))[0];if(!t){this.move(p);return;}if(this.target?.id!==t.id)this.cancel();this.target=t;this.attackOrder=true;this.destination=null;this.effect(t,'#e7c177');}
 spawn(){const hard=this.settings.difficulty==='hard',easy=this.settings.difficulty==='easy';const n=Math.floor(this.elapsed/(hard?0.9:easy?2.2:1.45));const kind=n%4===3?'circle':'line';const delay=easy?0.85:hard?0.42:0.62;if(kind==='circle'){this.dangers.push({...this.player,vx:0,vy:0,delay:delay+0.25,age:0,life:delay+0.5,radius:85,kind,hit:false,resolved:false});return;}const side=n%4;const origin=side===0?{x:40,y:140+(n*107)%600}:side===1?{x:1460,y:100+(n*71)%700}:side===2?{x:200+(n*131)%1100,y:55}:{x:150+(n*137)%1150,y:875};const a=Math.atan2(this.player.y-origin.y,this.player.x-origin.x),speed=easy?410:hard?690:540;const offsets=n%3===2?[-0.17,0,0.17]:[0];for(const o of offsets)this.dangers.push({...origin,vx:Math.cos(a+o)*speed,vy:Math.sin(a+o)*speed,delay,age:0,life:delay+3.8,radius:13,kind:'line',hit:false,resolved:false});}
 update(dt:number){if(this.status!=='running')return;this.previous={...this.player};this.elapsed+=dt;this.cooldown=Math.max(0,this.cooldown-dt);this.flash=Math.max(0,this.flash-dt);
  for(const t of this.targets){t.flash=Math.max(0,t.flash-dt);if(this.settings.mode==='mixed'){const bases=[{x:970,y:400},{x:1050,y:630},{x:550,y:270}];const b=bases[t.id-1];t.x=b.x+Math.sin(this.elapsed*0.65+t.id)*65;t.y=b.y+Math.cos(this.elapsed*0.5+t.id)*40;}}
  if(this.windupLeft>0){this.windupLeft-=dt;if(this.windupLeft<=0&&this.target){this.windupLeft=0;this.fired++;this.shotEvent++;this.flash=0.14;this.bolts.push({...this.player,target:this.target});this.effect(this.player,'#80ffdf');}}
  if(this.attackOrder&&this.target&&this.windupLeft<=0){if(distance(this.player,this.target)>this.settings.range){this.destination={...this.target};}else{this.destination=null;if(this.cooldown<=0){this.windupLeft=1/this.settings.attackSpeed*this.settings.windup/100;this.cooldown=1/this.settings.attackSpeed;this.angle=Math.atan2(this.target.y-this.player.y,this.target.x-this.player.x);}}}
  if(this.destination&&this.windupLeft<=0){const d=distance(this.player,this.destination),step=Math.min(d,this.settings.moveSpeed*dt);if(d>0.01){this.angle=Math.atan2(this.destination.y-this.player.y,this.destination.x-this.player.x);this.player.x+=Math.cos(this.angle)*step;this.player.y+=Math.sin(this.angle)*step;this.movingTime+=dt;}if(d<=step)this.destination=null;}
  for(const b of this.bolts){const d=distance(b,b.target);if(d<1400*dt){b.target.flash=0.17;this.effect(b.target,'#f6d895','60');b.x=-9999;}else{b.x+=(b.target.x-b.x)/d*1400*dt;b.y+=(b.target.y-b.y)/d*1400*dt;}}this.bolts=this.bolts.filter(b=>b.x>-9000);
  if(this.settings.mode!=='rhythm'){this.nextDanger-=dt;if(this.nextDanger<=0){this.spawn();this.nextDanger=this.settings.difficulty==='hard'?0.9:this.settings.difficulty==='easy'?2.2:1.45;}}
  for(const d of this.dangers){d.age+=dt;if(d.age<d.delay)continue;if(d.kind==='line'){const old={x:d.x,y:d.y};d.x+=d.vx*dt;d.y+=d.vy*dt;if(!d.hit&&segmentDistance({x:0,y:0},{x:old.x-this.previous.x,y:old.y-this.previous.y},{x:d.x-this.player.x,y:d.y-this.player.y})<d.radius+17)this.takeHit(d);}else if(!d.resolved){if(distance(d,this.player)<d.radius+17)this.takeHit(d);d.resolved=true;}
   if((d.age>d.life||d.x<-60||d.x>W+60||d.y<-60||d.y>H+60)&&!d.hit){this.dodged++;this.streak++;this.best=Math.max(this.best,this.streak);d.hit=true;}}
  this.dangers=this.dangers.filter(d=>d.age<=d.life&&d.x>=-60&&d.x<=W+60&&d.y>=-60&&d.y<=H+60);for(const e of this.effects)e.life-=dt;this.effects=this.effects.filter(e=>e.life>0);if(this.elapsed>=60){this.elapsed=60;this.status='ended';this.armed=false;}
 }
 takeHit(d:Danger){d.hit=true;this.hits++;this.hitEvent++;this.streak=0;this.effect(this.player,'#ff677d','HIT');}
 snapshot():Snapshot{const phase=this.armed?'AIMING':this.windupLeft>0?'WINDUP':this.cooldown>0?'RECOVERY':'READY';return{status:this.status,time:Math.max(0,60-this.elapsed),fired:this.fired,cancelled:this.cancelled,hits:this.hits,dodged:this.dodged,moved:this.elapsed?this.movingTime/this.elapsed*100:0,phase,progress:this.windupLeft>0?1-this.windupLeft/(1/this.settings.attackSpeed*this.settings.windup/100):1-this.cooldown*this.settings.attackSpeed,streak:this.streak,best:this.best};}
}
export class Arena extends Simulation{
 canvas:HTMLCanvasElement;ctx:CanvasRenderingContext2D;notify:(s:Snapshot)=>void;raf=0;last=0;acc=0;lastUI=0;audio:AudioContext|null=null;observer:ResizeObserver;inside=false;heldRight=false;listeners:(()=>void)[]=[];
 constructor(canvas:HTMLCanvasElement,settings:Settings,notify:(s:Snapshot)=>void){super(settings);this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false})!;this.notify=notify;this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);const on=(el:EventTarget,type:string,fn:EventListener)=>{el.addEventListener(type,fn);this.listeners.push(()=>el.removeEventListener(type,fn));};
  on(canvas,'contextmenu',e=>e.preventDefault());on(canvas,'pointermove',ev=>{this.point(ev as PointerEvent);if(this.heldRight&&this.inside)this.move(this.cursor);});on(canvas,'pointerenter',()=>{this.inside=true;});on(canvas,'pointerleave',()=>{this.inside=false;});on(window,'pointerup',()=>{this.heldRight=false;});on(window,'pointercancel',()=>{this.heldRight=false;});on(canvas,'pointerdown',ev=>{const e=ev as PointerEvent;this.point(e);if(!this.inside)return;canvas.focus({preventScroll:true});this.wakeAudio();if(e.button===2){e.preventDefault();this.heldRight=true;this.move(this.cursor);}else if(e.button===0&&this.armed)this.attack(this.cursor);});
  const keydown=(e:KeyboardEvent)=>this.handleKey(e);window.addEventListener('keydown',keydown,true);this.listeners.push(()=>window.removeEventListener('keydown',keydown,true));on(window,'blur',()=>this.pause());on(document,'visibilitychange',()=>{if(document.hidden)this.pause();});this.raf=requestAnimationFrame(t=>this.frame(t));}
 handleKey(e:KeyboardEvent){
  const target=e.target as HTMLElement|null;
  if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||target?.isContentEditable||target?.closest?.('input,textarea,select,[contenteditable="true"]'))return;
  const key=e.key?.toLowerCase();
  const code=(['KeyA','KeyS','Space','Enter','Escape'].includes(e.code)?e.code:'')||({a:'KeyA',s:'KeyS',' ':'Space',enter:'Enter',escape:'Escape'} as Record<string,string>)[key||'']||({65:'KeyA',83:'KeyS',32:'Space',13:'Enter',27:'Escape'} as Record<number,string>)[e.keyCode];
  if(code==='Enter'&&(this.status==='idle'||this.status==='ended')){e.preventDefault();this.start();return;}
  if(this.status!=='running'&&this.status!=='paused')return;
  if(code==='Space'){e.preventDefault();this.togglePause();return;}
  if(this.status!=='running')return;
  if(code==='KeyS'){e.preventDefault();this.stop();this.canvas.focus({preventScroll:true});this.notify(this.snapshot());return;}
  if(code==='KeyA'){
   e.preventDefault();this.heldRight=false;
   if(this.settings.quick){if(this.inside)this.attack(this.cursor);}else this.armed=true;
   this.canvas.focus({preventScroll:true});this.notify(this.snapshot());
  }
  if(code==='Escape'){e.preventDefault();if(this.armed)this.armed=false;else this.togglePause();}
 }
 override stop(){this.heldRight=false;super.stop();this.previous={...this.player};this.effect(this.player,'#a1ffdf','STOP');}
 override attack(p:Point){this.heldRight=false;super.attack(p);}
 configure(s:Settings){this.settings={...s};if(this.status==='idle'||this.status==='ended')this.resetTargets();}
 override start(){super.start();this.wakeAudio();this.canvas.focus({preventScroll:true});this.notify(this.snapshot());}
 pause(){if(this.status==='running'){this.status='paused';this.heldRight=false;this.notify(this.snapshot());}}
 togglePause(){if(this.status==='running')this.pause();else if(this.status==='paused'){this.status='running';this.canvas.focus({preventScroll:true});this.notify(this.snapshot());}}
 point(e:PointerEvent){const r=this.canvas.getBoundingClientRect(),scale=Math.min(r.width/W,r.height/H);this.cursor={x:(e.clientX-r.left-(r.width-W*scale)/2)/scale,y:(e.clientY-r.top-(r.height-H*scale)/2)/scale};this.inside=this.cursor.x>=0&&this.cursor.x<=W&&this.cursor.y>=0&&this.cursor.y<=H;}
 wakeAudio(){if(!this.audio&&this.settings.sound)this.audio=new AudioContext();if(this.audio?.state==='suspended')void this.audio.resume();}
 tone(freq:number,duration:number){if(!this.settings.sound||!this.audio)return;const o=this.audio.createOscillator(),g=this.audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,this.audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*0.5,this.audio.currentTime+duration);g.gain.setValueAtTime(0.04,this.audio.currentTime);g.gain.exponentialRampToValueAtTime(0.001,this.audio.currentTime+duration);o.connect(g);g.connect(this.audio.destination);o.start();o.stop(this.audio.currentTime+duration);}
 resize(){const r=this.canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.round(r.width*dpr);this.canvas.height=Math.round(r.height*dpr);}
 frame(t:number){const dt=this.last?Math.min((t-this.last)/1000,0.1):0;this.last=t;this.acc+=dt;const shots=this.shotEvent,hits=this.hitEvent;while(this.acc>=STEP){this.update(STEP);this.acc-=STEP;}if(shots!==this.shotEvent)this.tone(850,0.08);if(hits!==this.hitEvent)this.tone(150,0.18);this.draw(this.acc/STEP);if(t-this.lastUI>65){this.notify(this.snapshot());this.lastUI=t;}this.raf=requestAnimationFrame(n=>this.frame(n));}
 draw(alpha:number){const c=this.ctx,cw=this.canvas.width,ch=this.canvas.height;c.setTransform(1,0,0,1,0,0);c.fillStyle='#0b1418';c.fillRect(0,0,cw,ch);const scale=Math.min(cw/W,ch/H);c.translate((cw-W*scale)/2,(ch-H*scale)/2);c.scale(scale,scale);const p=this.status==='running'?{x:this.previous.x+(this.player.x-this.previous.x)*alpha,y:this.previous.y+(this.player.y-this.previous.y)*alpha}:this.player;
  const bg=c.createRadialGradient(740,450,30,740,450,850);bg.addColorStop(0,'#172c30');bg.addColorStop(1,'#0a151b');c.fillStyle=bg;c.fillRect(0,0,W,H);c.lineWidth=1;c.strokeStyle='#29404655';for(let x=30;x<W;x+=70){c.beginPath();c.moveTo(x,35);c.lineTo(x,H-35);c.stroke();}for(let y=35;y<H;y+=70){c.beginPath();c.moveTo(30,y);c.lineTo(W-30,y);c.stroke();}c.strokeStyle='#55737540';c.strokeRect(30,35,W-60,H-70);c.setLineDash([6,12]);this.circle(750,460,320,'#466c6e44');this.circle(750,460,90,'#466c6e44');c.setLineDash([]);c.fillStyle='#77918b66';c.font='14px monospace';c.fillText('SECTOR 01 / ORBWALK',65,80);c.fillText('TRAINING FIELD',W-225,H-60);
  if(this.settings.showRange||this.armed){if(this.armed){c.fillStyle='#ffd78c09';c.beginPath();c.arc(p.x,p.y,this.settings.range,0,Math.PI*2);c.fill();}c.setLineDash(this.armed?[]:[8,10]);this.circle(p.x,p.y,this.settings.range,this.armed?'#ffd78ce0':'#69d4c185',this.armed?3:2);c.setLineDash([]);}if(this.destination){c.strokeStyle='#70dfca40';c.setLineDash([5,10]);c.beginPath();c.moveTo(p.x,p.y);c.lineTo(this.destination.x,this.destination.y);c.stroke();c.setLineDash([]);this.circle(this.destination.x,this.destination.y,9,'#6ef7d3');}
  for(const d of this.dangers){const tele=d.age<d.delay;if(d.kind==='circle'){c.save();if(!tele)c.globalAlpha=Math.max(0,1-(d.age-d.delay)/(d.life-d.delay));c.fillStyle=tele?'#ff546220':'#ff6b6520';c.beginPath();c.arc(d.x,d.y,d.radius,0,Math.PI*2);c.fill();this.circle(d.x,d.y,d.radius+(tele?0:(d.age-d.delay)*90),'#ff7c7c',2);if(tele)this.circle(d.x,d.y,d.radius*d.age/d.delay,'#ff7c7c88',2);c.restore();}else{const len=Math.hypot(d.vx,d.vy),nx=d.vx/len,ny=d.vy/len;if(tele){c.lineWidth=26;c.strokeStyle='#ff647019';c.beginPath();c.moveTo(d.x,d.y);c.lineTo(d.x+nx*1900,d.y+ny*1900);c.stroke();c.lineWidth=1;c.strokeStyle='#ff829080';c.setLineDash([9,12]);c.stroke();c.setLineDash([]);this.circle(d.x,d.y,22,'#ff8794',3);this.circle(d.x,d.y,29*d.age/d.delay,'#ff8794',2);}else{c.lineCap='round';c.lineWidth=26;c.strokeStyle=d.hit?'#8e566b66':'#ff516855';c.beginPath();c.moveTo(d.x-nx*70,d.y-ny*70);c.lineTo(d.x,d.y);c.stroke();c.lineWidth=9;c.strokeStyle=d.hit?'#a56876':'#ff9da4';c.beginPath();c.moveTo(d.x-nx*35,d.y-ny*35);c.lineTo(d.x,d.y);c.stroke();c.lineCap='butt';}}}
  for(const t of this.targets){c.save();c.translate(t.x,t.y);c.fillStyle='#00000040';c.beginPath();c.ellipse(0,12,31,17,0,0,Math.PI*2);c.fill();if(this.target?.id===t.id)this.circle(0,0,39,'#f4d18a',2);this.circle(0,0,28,'#b99661',2);c.rotate(Math.PI/4);c.fillStyle=t.flash>0?'#fff5cb':'#715c3a';c.strokeStyle='#efd39b';c.lineWidth=2;c.fillRect(-15,-15,30,30);c.strokeRect(-15,-15,30,30);c.fillStyle='#f8da94';c.fillRect(-5,-5,10,10);c.restore();c.fillStyle='#d9c59f';c.font='12px monospace';c.textAlign='center';c.fillText('TARGET 0'+t.id,t.x,t.y-48);c.fillStyle=t.flash?'#fff2be':'#c7a46b';c.fillRect(t.x-28,t.y-38,56,4);c.textAlign='left';}
  for(const b of this.bolts){const a=Math.atan2(b.target.y-b.y,b.target.x-b.x);c.strokeStyle='#8dffe4';c.lineWidth=5;c.beginPath();c.moveTo(b.x-Math.cos(a)*25,b.y-Math.sin(a)*25);c.lineTo(b.x,b.y);c.stroke();this.circle(b.x,b.y,5,'#e5fff7',2);}
  c.save();c.translate(p.x,p.y);c.fillStyle='#00000050';c.beginPath();c.ellipse(0,15,28,13,0,0,Math.PI*2);c.fill();this.circle(0,0,24,'#8bf0d4',2);c.rotate(this.angle);c.fillStyle=this.flash>0?'#ecfff7':'#51cdb2';c.beginPath();c.moveTo(23,0);c.lineTo(-12,-15);c.lineTo(-7,0);c.lineTo(-12,15);c.closePath();c.fill();c.fillStyle='#ddfff4';c.beginPath();c.arc(0,0,6,0,Math.PI*2);c.fill();c.restore();if(this.windupLeft>0){c.lineWidth=5;c.strokeStyle='#ffd18a';c.beginPath();c.arc(p.x,p.y,33,-Math.PI/2,-Math.PI/2+Math.PI*2*(1-this.windupLeft/(1/this.settings.attackSpeed*this.settings.windup/100)));c.stroke();}else if(this.flash>0)this.circle(p.x,p.y,30+(0.14-this.flash)*130,'#a1ffdf',3);c.fillStyle='#79f1cd';c.fillRect(p.x-22,p.y-44,44,4);c.font='12px monospace';c.textAlign='center';c.fillText(this.armed?'CLICK TO ATTACK':'YOU',p.x,p.y+48);c.textAlign='left';
  for(const e of this.effects){c.globalAlpha=e.life/e.max;if(e.text){c.font='bold 19px monospace';c.textAlign='center';c.fillStyle=e.color;c.fillText(e.text,e.x,e.y-40-(e.max-e.life)*42);c.textAlign='left';}else this.circle(e.x,e.y,10+(1-e.life/e.max)*30,e.color,2);}c.globalAlpha=1;if(this.inside&&this.status==='running'){const cur=this.cursor;c.strokeStyle=this.armed?'#ffd78c':'#a4f1df';c.lineWidth=1.5;this.circle(cur.x,cur.y,this.armed?14:5,c.strokeStyle);if(this.armed){c.setLineDash([3,10]);this.circle(cur.x,cur.y,220,'#ffd78c25');c.setLineDash([]);}for(const [x,y]of[[1,0],[-1,0],[0,1],[0,-1]]){c.beginPath();c.moveTo(cur.x+x*10,cur.y+y*10);c.lineTo(cur.x+x*20,cur.y+y*20);c.stroke();}}}
 circle(x:number,y:number,r:number,color:string,width=1){this.ctx.beginPath();this.ctx.arc(x,y,Math.max(0,r),0,Math.PI*2);this.ctx.strokeStyle=color;this.ctx.lineWidth=width;this.ctx.stroke();}
 destroy(){cancelAnimationFrame(this.raf);this.observer.disconnect();this.listeners.forEach(f=>f());void this.audio?.close();}
}
